-- HEADER
--ALTER PROC [PROC_GF_PF_TARGET_SUMMARY_HEADER] @PARTNER_ID VARCHAR(10), @RP_FROM VARCHAR(10), @RP_TO VARCHAR(10)
--AS
--BEGIN
--	DECLARE @PART_ID AS VARCHAR(MAX)
--	IF @PARTNER_ID <> 'All'
--		BEGIN
--			SET @PART_ID = ' AND B.PARTNER_ID = ' + @PARTNER_ID
--		END
--	ELSE
--		BEGIN
--			SET @PART_ID = ' '
--		END
	
--	DECLARE @RPFROM AS VARCHAR(MAX)
--	IF @RP_FROM Is Not Null
--		BEGIN
--			SET @RPFROM = 'AND C.PERIOD >= (SELECT PERIOD FROM [GF_MONTH] WHERE REPORTING_PERIOD = ''' + @RP_FROM + ''')'
--		END
--	ELSE
--		BEGIN
--			SET @RPFROM = ' '
--		END

--	DECLARE @RPTO AS VARCHAR(MAX)
--	IF @RP_TO Is Not Null
--		BEGIN
--			SET @RPTO = 'AND C.PERIOD <= (SELECT PERIOD FROM [GF_MONTH] WHERE REPORTING_PERIOD = ''' + @RP_TO + ''')'
--		END
--	ELSE
--		BEGIN
--			SET @RPTO = ' '
--		END

--	EXEC('
--		SELECT 
--			DISTINCT B.REPORTING_PERIOD AS HEADER
--			--A.PF_INDICATOR_DESC,
--			--B.REPORTING_PERIOD,
--			--C.PERIOD
--		FROM [GF_PF_INDICATOR_NEW] AS A
--		JOIN [GF_PF_INDICATOR_VALUE_NEW] AS B ON A.PF_INDICATOR_ID = B.PF_INDICATOR_ID
--		JOIN [GF_MONTH] AS C ON B.REPORTING_PERIOD = C.REPORTING_PERIOD
--		WHERE (1=1) '
--			+ @PART_ID + @RPFROM + @RPTO + '
--	')
--END

--EXEC PROC_GF_PF_TARGET_SUMMARY_HEADER 'All', 'P7M1', 'P15M4'




ALTER PROC [PROC_GF_PF_TARGET_SUMMARY] @PARTNER_ID VARCHAR(10), @RP_FROM VARCHAR(10), @RP_TO VARCHAR(10)
AS
BEGIN
	
	DECLARE @RPFROM AS VARCHAR(MAX)
	IF @RP_FROM Is Not Null
		BEGIN
			SET @RPFROM = 'AND C.PERIOD >= (SELECT PERIOD FROM [GF_MONTH] WHERE REPORTING_PERIOD = ''' + @RP_FROM + ''')'
		END
	ELSE
		BEGIN
			SET @RPFROM = ' '
		END

	DECLARE @RPTO AS VARCHAR(MAX)
	IF @RP_TO Is Not Null
		BEGIN
			SET @RPTO = 'AND C.PERIOD <= (SELECT PERIOD FROM [GF_MONTH] WHERE REPORTING_PERIOD = ''' + @RP_TO + ''')'
		END
	ELSE
		BEGIN
			SET @RPTO = ' '
		END


	DECLARE @SQLQuery AS VARCHAR(MAX)
	SET @SQLQuery = ('SELECT 		
						A.PF_INDICATOR_ID,
						A.PF_INDICATOR_DESC AS PF_INDICATOR,
						B.REPORTING_PERIOD AS RP_PERIOD,
						B.TARGET AS TARGET,
						SUM(B.TARGET) OVER (PARTITION BY A.PF_INDICATOR_ID) AS TOTAL
					FROM [GF_PF_INDICATOR_NEW] AS A
					JOIN [GF_PF_INDICATOR_VALUE_NEW] AS B ON A.PF_INDICATOR_ID = B.PF_INDICATOR_ID
					JOIN [GF_MONTH] AS C ON B.REPORTING_PERIOD = C.REPORTING_PERIOD
					WHERE B.PARTNER_ID = CONVERT(VARCHAR(10),' +@PARTNER_ID+')'
						+ @RPFROM + @RPTO + '
					')

		DECLARE @HEADER VARCHAR(MAX)
		SELECT  @HEADER = T.HEADER FROM( SELECT ( SELECT 
							DISTINCT B.REPORTING_PERIOD+','
						FROM [GF_PF_INDICATOR_NEW] AS A
						JOIN [GF_PF_INDICATOR_VALUE_NEW] AS B ON A.PF_INDICATOR_ID = B.PF_INDICATOR_ID
						JOIN [GF_MONTH] AS C ON B.REPORTING_PERIOD = C.REPORTING_PERIOD
						WHERE
							B.PARTNER_ID = @PARTNER_ID AND
							C.PERIOD >= (CASE WHEN @RP_FROM IS NOT NULL THEN ( (SELECT PERIOD FROM [GF_MONTH] WHERE REPORTING_PERIOD = @RP_FROM)) ELSE '' END) AND 
							C.PERIOD <= (CASE WHEN @RP_TO IS NOT NULL THEN ( (SELECT PERIOD FROM [GF_MONTH] WHERE REPORTING_PERIOD = @RP_TO)) ELSE '' END )
						FOR XML PATH ('')) HEADER)T
--PRINT(@HEADER)
	IF LEN(@HEADER) > 0
	BEGIN
	SELECT  @HEADER = LEFT( @HEADER, LEN(@HEADER)-1) 
	

	DECLARE @DATA INT = 0
	SELECT @DATA = (SELECT COUNT(PF_INDICATOR_ID) FROM [GF_PF_INDICATOR_VALUE_NEW] WHERE PARTNER_ID = @PARTNER_ID)
	
	
		IF @DATA > 0
			BEGIN
				EXEC('
					SELECT 
						ROW_NUMBER() OVER (Order by PF_INDICATOR_ID) AS SN,
						PF_INDICATOR AS INDICATOR,
						'+@HEADER+',
						TOTAL
					FROM ('
						+ @SQLQuery +
					') AS S
					PIVOT
					(
						SUM(S.TARGET)
						FOR [RP_PERIOD] IN ('+ @HEADER +')
					) AS piv
				')
			END

	END

END

-- EXEC [PROC_GF_PF_TARGET_SUMMARY] '42', 'P12M1', 'P15M2'